### ISSUE TITLE
Powered soil not dropping upgrades

### ISSUE THREAD

**Issue by akvgergo** [jaredlll08/Fluxed-Crystals#42] opened 2015-03-06 17:34 UTC
^title says it. The powered soil doesn't seem to drop upgrades when broken.
On another note, it gives stone sounds on placement, on mining, and when it's broken. I think it should give dirt sounds, but that's just my personal opinion :P

**Comment by mellamokb** [comment] 2015-03-08 19:42
akvgergo: This is a duplicate of https://github.com/jaredlll08/Fluxed-Crystals/issues/34 which has been marked resolved.

**Comment by akvgergo** [comment] 2015-03-08 22:44
Right. Sorry, I didn't check the closed issues. I'm leaving this open anyway, in case somebody wants to make another report. An author can close this if they think this is unnecessary, or if they release the version with the fix.

**Closed** 2015-04-19 13:06 UTC
