### ISSUE TITLE
Gem refiner/cutter stop working untill opening GUI

### ISSUE THREAD

**Issue by Rodg88** [jaredlll08/Fluxed-Crystals#30] opened 2015-02-11 07:37 UTC
Sometimes the cutter and refiner stop processing, without even leaving the chunk. I insert the rough chunks into the cutter with an EIO item buffer set to push/pull, which also extracts the smooth shards. The refiner is on the other side of the item buffer, which is also set to push/pull.
It happens reliably to both machines when I replace the blocks, opening the GUI once to insert 3 speed upgrades, then inserting shards into the item buffer. The cutters and refiners don't start working until I open their GUIs with shards in them. The refiners also seem to stop randomly mid-process occasionally.

**Comment by Soulrift** [comment] 2015-02-12 23:28
Does the issue occur without the upgrades?

**Comment by Rodg88** [comment] 2015-02-13 03:56
Yep, just happened again with the following steps:
place item buffer, setting 2 sides to push/pull.
place cutter and refiner, each on a push/pull side of item buffer (and on power cable)
without interacting with cutter/refiner, insert rough shards into item buffer, and they get pushed into the cutter, confirmed by holo-inventory showing rough shards in the cutter (and waila showing it's powered).
Wait, and nothing happens. Open and close the cutter's GUI, and it starts processing. Same thing happens with smooth shards in the refiner, even when just getting 1 shard at a time as the cutter processes.This was with b41

**Comment by Rodg88** [comment] 2015-02-13 04:10
Also happens with item conduits, and if I break the buffer/conduit after shards are inserted. And it still happens if I open the GUI before I insert shards too.

**Comment by ogredude** [comment] 2015-03-03 01:22
I'm also having this same issue. 0.0.5d

**Comment by jaredlll08** [comment] 2015-03-04 12:09
I can't reproduce this error :/

**Comment by Flabadab** [comment] 2015-03-04 13:14
This happens to me too using item conduits or if logging out and back in while the machine is processing. I've tried several things and below is what I've found:

Steps:
Place Gem Refiner/Cutter
Supply Power
Place item duct on top of Cutter/Refiner
Place Chest on top of item Duct
Set both ends of item duct to insert/extract
Fill chest with shards

Item conduit extracts shards and places them in Refiner/Cutter.
No processing happens.
Open GUI.
Processing then starts and will continue to process until one of the following things happen:
 - The machine runs out of power (Supplying power after it stops doesn't get it going again unless you open the gui)
 - The machine runs out of items to process (Adding items to the chest will fill the machine but processing doesn't start until you open the GUI again)
 - Logging out and back in (SP) or restarting the server (MP) (Processing will only start again once GUI is opened)
 - While exploring, if the chunk that the machine is in is unloaded, processing stops (as one expects) but will not start again once the chunk is reloaded until you open the GUI.

(Side Note: If you Open the Gui at least once before items are added from the chest processing seems fine until one of the above conditions)

**Comment by iarspider** [comment] 2015-03-13 13:13
The fix by @Flabadab doesn't help :(

**Comment by Flabadab** [comment] 2015-03-13 16:27
@iarspider, sorry, the fix I provided was only for the gem refiner. I've made a pull request for the other blocks that I updated.

**Comment by krakentoa** [comment] 2015-03-15 23:46
with the 0.5e update things seem fixed. i never had much trouble with the cutter (maybe I previously had a version with the fix for that), but the refiner was so slow I had to parallelize:
![2015-03-15_23 40 58](https://cloud.githubusercontent.com/assets/11034266/6658797/0bc6f1f4-cb6d-11e4-80ca-b98dd1be5b0f.png)
Last time I checked, the refiners could keep track of only one type of smooth shard; my solution is a set of refiners for each type of smooth shards; this was mildly entertaining to automate.

**Comment by jaredlll08** [comment] 2015-03-15 23:54
So is this issue resolved? Can I finnaly close it??

**Comment by krakentoa** [comment] 2015-03-15 23:57
idk about all the other stuff: sever restart, chunk reload, ect. all I know is that suddenly the machines are blazing fast. I did notice that when I opened the gui, machines seemed to start working, which is why I commented here. then I noticed a fix had been submitted, so I updated the mod and my problems, which aren't exactly the ones above, seem fixed.

**Comment by krakentoa** [comment] 2015-03-16 14:43
Ok, after some time I can say that gem refiners are extremely faster than gem cutters. This might due to a bug or not. It is also very impractical: I got an input of 3-5 rough shards/ second and those 12 gem cutters in the upper left in the picture above can't handle it (they are all upgraded).

**Comment by jaredlll08** [comment] 2015-03-17 12:46
Pulled the fix :)

**Closed by jaredlll08** 2015-03-17 12:46 UTC
Labels: bug

**Comment by krakentoa** [comment] 2015-03-17 23:40
uh i built from spurce, possibly tht invalidates my crash but here it is : http://pastebin.com/wfp41j9k
i'm setting crafting to true for now.

**Comment by lanord** [comment] 2015-04-15 01:20
Sorry to reopen this but i still got this behavior with the gem cutter with or without the speed upgrade.

Playing the MA^4 pack
Version is  Fluxed-Crystals [0.0.5h] and 	ttCore-MC1.7.10-0.1.1-75.jar.

If you need more info tell me.
